In [1]:
# importing pandas and dataset file


import pandas as pd

df = pd.read_csv('/content/train.csv')

df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

a) Look for the missing values in all the columns and either impute them (replace with mean, median, or mode) or drop them. Justify your action for this task.

In [2]:
# check what columns have missing values and count of them.


print(df.isnull().sum())

print(df.dtypes)

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64
Unnamed: 0             int64
Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price             object
Price                float64
dtype: object

b) Remove the units from some of the attributes and only keep the numerical values (for example remove kmpl from “Mileage”, CC from “Engine”, bhp from “Power”, and lakh from “New_price”).

In [3]:
df['Mileage'] = df['Mileage'].str.replace(r'\s+[a-zA-Z/]+', '', regex=True)
df['Engine'] = df['Engine'].str.replace(r'\s+CC', '', regex=True)
df['Power'] = df['Power'].str.replace(r'\s+bhp', '', regex=True)
df['New_Price'] = df['New_Price'].str.replace(r'\s+Lakh', '', regex=True)

df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13,1199,88.7,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2,1968,140.8,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461,63.1,5.0,NaN,3.50

In [7]:
# replace the missing values in Mileage, Engine, Power and Seats columns


# Convert columns to numeric (stripping out non-numeric characters where necessary)
df['Mileage'] = pd.to_numeric(df['Mileage'].str.extract('(\d+\.?\d*)')[0], errors='coerce')
df['Engine'] = pd.to_numeric(df['Engine'].str.extract('(\d+\.?\d*)')[0], errors='coerce')
df['Power'] = pd.to_numeric(df['Power'].str.extract('(\d+\.?\d*)')[0], errors='coerce')

# Fill missing numeric values with median
df['Mileage'].fillna(df['Mileage'].median(), inplace=True)
df['Engine'].fillna(df['Engine'].median(), inplace=True)
df['Power'].fillna(df['Power'].median(), inplace=True)

# Fill missing categorical values with mode
df['Seats'].fillna(df['Seats'].mode()[0], inplace=True)

<ipython-input-7-1afa04c7e10e>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Mileage'].fillna(df['Mileage'].median(), inplace=True)
<ipython-input-7-1afa04c7e10e>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Engine'].fillna(df['Engine'].median(), inplace=True)
<ipython-input-7-1afa04c7e10e>:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Power'].fillna(df['Power'].median(), inplace=True)
<ipython-input-7-1afa04c7e10e>:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Seats'].fillna(df['Seats'].mode()[0], inplace=True)

In [17]:
# dropping the 'New_Price' column since there are lot of missing values


df.drop(columns=['New_Price'], inplace=True, errors='ignore')

print(df.isnull().sum())

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

c) Change the categorical variables (“Fuel_Type” and “Transmission”) into numerical one hot encoded value.

In [18]:

fuel_mapping = {'Diesel': 0, 'Petrol': 1, 'Electric': 2}
df['Fuel_Type'] = df['Fuel_Type'].replace(fuel_mapping)

transmission_mapping = {'Manual': 0, 'Automatic': 1}
df['Transmission'] = df['Transmission'].replace(transmission_mapping)

df.head()

<ipython-input-18-d787a989f176>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Fuel_Type'] = df['Fuel_Type'].replace(fuel_mapping)
<ipython-input-18-d787a989f176>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Transmission'] = df['Transmission'].replace(transmission_mapping)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50

In [19]:

# getting current year to calculate age of the car


from datetime import datetime

current_year = datetime.now().year

d) Create one more feature and add this column to the dataset (you can use mutate function in R for this). For example, you can calculate the current age of the car by subtracting “Year” value from the current year.

In [20]:
df['Age_of_Car'] = current_year - df['Year']


df['Power_per_Liter'] = (df['Power'].astype(float) / df['Mileage'].astype(float)).round(2)


df['Mileage_per_Seat'] = (df['Mileage'].astype(float) / df['Seats'].astype(float)).round(2)


df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50,10,6.42,3.93
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50,14,6.82,2.60
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00,13,4.27,2.97
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74,12,9.26,3.04
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50,12,2.73,4.62

In [23]:
preprocessed_csv_file = '/content/preprocessed_data.csv'
df.to_csv(preprocessed_csv_file, index=False)

e) Perform select, filter, rename, mutate, arrange and summarize with group by operations (or their equivalent operations in python) on this dataset.

In [24]:

# selecting the columns


required_columns = ['Name', 'Mileage', 'Engine', 'Seats']
df_selected = df[required_columns]
df_selected.head()

                               Name  Mileage  Engine  Seats
0  Hyundai Creta 1.6 CRDi SX Option    19.67  1582.0    5.0
1                      Honda Jazz V    13.00  1199.0    5.0
2                 Maruti Ertiga VDI    20.77  1248.0    7.0
3   Audi A4 New 2.0 TDI Multitronic    15.20  1968.0    5.0
4            Nissan Micra Diesel XV    23.08  1461.0    5.0

In [25]:
selected_csv_file = '/content/selected_data.csv'
df_selected.to_csv(selected_csv_file, index=False)

In [26]:
# filtering rows based on conditions


filtered_df = df[(df['Mileage'].astype(float) > 20) & (df['Engine'].astype(float) < 1500)]
filtered_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00,13,4.27,2.97
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50,12,2.73,4.62
7,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,0,0,Second,22.30,1248.0,74.00,5.0,1.95,13,3.32,4.46
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,1,0,First,21.56,1462.0,103.25,5.0,9.95,7,4.79,4.31
10,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,0,0,First,25.20,1248.0,74.00,5.0,5.60,10,2.94,5.04

In [27]:
filtered_csv_file = '/content/filtered_data.csv'
filtered_df.to_csv(filtered_csv_file, index=False)

In [28]:
# renaming column


renamed_df = df.rename(columns={'Power_per_Liter': 'Power_per_Fuel'})
renamed_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Fuel,Mileage_per_Seat
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50,10,6.42,3.93
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50,14,6.82,2.60
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00,13,4.27,2.97
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74,12,9.26,3.04
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50,12,2.73,4.62

In [29]:
#Arrange
# sorting the df based on age of the car and Mileage features


sorted_df = df.sort_values(by=['Age_of_Car', 'Mileage'], ascending=[True, False])
sorted_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
4198,4328,Maruti Swift DDiS VDI,Coimbatore,2019,41075,0,0,First,28.40,1248.0,74.0,5.0,8.40,6,2.61,5.68
984,1018,Maruti Swift Dzire VDI Optional,Kochi,2019,18592,0,0,First,26.59,1248.0,74.0,5.0,8.51,6,2.78,5.32
4267,4399,Maruti Swift Dzire AMT ZDI,Chennai,2019,65000,0,1,First,26.59,1248.0,74.0,5.0,6.75,6,2.78,5.32
5405,5560,Renault KWID RXT Optional,Kochi,2019,6568,1,0,First,25.17,799.0,53.3,5.0,5.09,6,2.12,5.03
5628,5789,Renault KWID RXL,Kochi,2019,7858,1,0,First,25.17,799.0,53.3,5.0,3.80,6,2.12,5.03

In [30]:
arranged_csv_file = '/content/arranged_data.csv'
sorted_df.to_csv(arranged_csv_file, index=False)


df['Mileage'] = df['Mileage'].astype(float)

In [31]:
#Transform function

# To know the mean mileage based on location


df['Avg_Mileage_Location'] = df.groupby('Location')['Mileage'].transform('mean')
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat,Avg_Mileage_Location
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50,10,6.42,3.93,17.886576
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50,14,6.82,2.60,18.236576
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00,13,4.27,2.97,18.236576
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74,12,9.26,3.04,17.844200
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50,12,2.73,4.62,19.189777

In [32]:
transformed_csv_file = '/content/transformed_data.csv'
df.to_csv(transformed_csv_file, index=False)

In [33]:
#Summarize

# Getting the mean mileage based on fuel type


grouped_df = df.groupby('Fuel_Type').agg({'Mileage': 'mean'}).sort_values(by='Mileage', ascending=False)
grouped_df.head()

             Mileage
Fuel_Type
0          18.652661
2          18.190000
1          17.576509

In [34]:

summary_csv_file = '/content/summary_data.csv'
grouped_df.to_csv(summary_csv_file, index=False)